-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-03 18:31:11 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Books 
    ( 
     book_id  NUMBER  NOT NULL , 
     title    VARCHAR2 (100)  NOT NULL , 
     rating   NUMBER (2)  NOT NULL , 
     Books_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Books 
    ADD CONSTRAINT Books_PK PRIMARY KEY ( Books_ID ) ;

CREATE TABLE Patrons 
    ( 
     p_id       NUMBER  NOT NULL , 
     name       VARCHAR2 (40)  NOT NULL , 
     address    VARCHAR2 (70)  NOT NULL , 
     Patrons_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Patrons 
    ADD CONSTRAINT Patrons_PK PRIMARY KEY ( Patrons_ID ) ;

CREATE TABLE Transaction 
    ( 
     t_id               DATE  NOT NULL , 
     t_date             DATE  NOT NULL , 
     t_type             VARCHAR2 (20)  NOT NULL , 
     Books_Books_ID     NUMBER  NOT NULL , 
     Patrons_Patrons_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Transaction 
    ADD CONSTRAINT Transaction_Books_FK FOREIGN KEY 
    ( 
     Books_Books_ID
    ) 
    REFERENCES Books 
    ( 
     Books_ID
    ) 
;

ALTER TABLE Transaction 
    ADD CONSTRAINT Transaction_Patrons_FK FOREIGN KEY 
    ( 
     Patrons_Patrons_ID
    ) 
    REFERENCES Patrons 
    ( 
     Patrons_ID
    ) 
;

CREATE SEQUENCE Books_Books_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Books_Books_ID_TRG 
BEFORE INSERT ON Books 
FOR EACH ROW 
WHEN (NEW.Books_ID IS NULL) 
BEGIN 
    :NEW.Books_ID := Books_Books_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Patrons_Patrons_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Patrons_Patrons_ID_TRG 
BEFORE INSERT ON Patrons 
FOR EACH ROW 
WHEN (NEW.Patrons_ID IS NULL) 
BEGIN 
    :NEW.Patrons_ID := Patrons_Patrons_ID_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              4
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          2
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
